/* ==================================================================
   64 · Konsole: Lager und QR-Codes
   Alle Kommissionen im Lager, der Stand je Position, der QR-Bogen zum
   Drucken – und der QR-Code, mit dem das Handy die App oeffnet.
   ================================================================== */
Desk.seiten.lager = () => {
  const heute = D.heute();
  const auftr = DB.auftraege.filter(a => !['archiviert', 'storniert'].includes(a.status) && Q.lagerpositionenVon(a.id).length).sort((x, y) => (Dom.AUFTRAG_FLUSS.indexOf(x.status) - Dom.AUFTRAG_FLUSS.indexOf(y.status)));
  const alle = DB.lagerpositionen.filter(lp => auftr.some(a => a.id === lp.auftragId));
  const n = s => alle.filter(x => x.status === s).length;
  const app = Mail.link('', '').replace(/\?=$/, '');
  const offen = S.ui.lagerOffen || (auftr[0] || {}).id;
  return `<div class="pg">
    <div class="kpis"><div class="kpi"><span class="lbl">Erwartet</span><span class="val">${n('erwartet')}</span><span class="dt">${alle.filter(x => x.status === 'erwartet' && Dom.terminVon(Q.bestellung(x.bestellungId) || { planTermin: heute }) < heute).length} überfällig</span></div><div class="kpi"><span class="lbl">Im Lager</span><span class="val">${n('eingetroffen')}</span><span class="dt">${auftr.filter(a => a.status === 'bereit' || a.status === 'terminiert').length} Kommissionen komplett</span></div><div class="kpi ${n('beschaedigt') ? 'hot' : ''}"><span class="lbl">Beschädigt</span><span class="val">${n('beschaedigt')}</span><span class="dt">unter Vorbehalt, Ersatz angefordert</span></div><div class="kpi"><span class="lbl">Ausgeliefert</span><span class="val">${n('ausgeliefert')}</span><span class="dt">an Montage</span></div></div>
    <div class="split" style="grid-template-columns:minmax(0,1.4fr) minmax(0,1fr)">
      <div class="stack">${auftr.map(a => { const lps = Q.lagerpositionenVon(a.id); const da = lps.filter(x => x.status !== 'erwartet').length; const k = Q.kunde(a.kundeId); const t = Q.termin(a.terminId); const ist = offen === a.id; return `<div class="card"><button class="card-h" style="width:100%;text-align:left;cursor:pointer" data-act="lagerk.auf" data-id="${a.id}"><h3>K-${h(a.nr.slice(-4))} · ${h(Dom.kundeName(k))} <small style="font-weight:500;color:var(--txt-3)">${h(a.nr)}</small></h3><div class="row"><span class="chip st st-${a.status}">${Dom.statusText(a.status)}</span><span class="chip ${da === lps.length ? 'ok' : ''}">${da}/${lps.length}</span>${ic(ist ? 'i-x' : 'i-weiter')}</div></button>
        ${ist ? `<div class="card-b"><div class="bar ${da === lps.length ? 'ok' : ''}" style="margin-bottom:10px"><i style="width:${Math.round(da / lps.length * 100)}%"></i></div>${t ? `<div class="banner ok" style="margin-bottom:10px"><span class="ic">${ic('i-werkzeug')}</span><div><b>Montage ${Fmt.datum(t.datum)}</b> – Kommission für ${h((Q.partner(a.partnerId) || {}).name || 'Partner')} bereitstellen.</div></div>` : ''}<div class="tbl-scroll"><table class="tbl"><thead><tr><th>Position</th><th>Lieferant</th><th>Status</th><th>Platz</th><th></th></tr></thead><tbody>${lps.map(lp => { const b = Q.bestellung(lp.bestellungId); return `<tr><td>${lp.menge > 1 ? lp.menge + '× ' : ''}${h(lp.name)}<br><small class="mono" style="color:var(--txt-3)">${h(lp.code)}</small></td><td><small>${h((Q.lieferant((b || {}).lieferantId) || {}).kuerzel || '')}${b && lp.status === 'erwartet' ? ' · ' + Fmt.relativ(Dom.terminVon(b)) : ''}</small></td><td><span class="chip st dot st-${lp.status}">${Dom.statusText(lp.status)}</span></td><td class="mono">${h(lp.lagerplatz || '–')}</td><td class="r"><button class="btn sm ghost icon" data-act="lagerk.qr" data-id="${lp.id}" title="QR-Code gross anzeigen">${ic('i-qr')}</button>${lp.status === 'erwartet' ? `<button class="btn sm ghost" data-act="auftrag.scanSim" data-id="${lp.id}">Buchen</button>` : ''}</td></tr>`; }).join('')}</tbody></table></div><div class="row" style="margin-top:10px"><button class="btn primary" data-act="doc.qrbogen" data-id="${a.id}">${ic('i-drucken')} QR-Bogen drucken</button><a class="btn ghost" href="#/auftrag/${a.id}/lager">Auftrag öffnen</a></div></div>` : ''}</div>`; }).join('')}</div>
      <div class="stack">
        <div class="card"><div class="card-h"><h3>Lager-App auf dem Handy</h3></div><div class="card-b"><div class="qr-big" style="padding:6px">${BWQR.svg(app, { size: 220, margin: 2 })}<small style="color:var(--txt-2);text-align:center;line-height:1.5">Mit der Handy-Kamera scannen, dann Code <b>98765</b>. Für Live-Abgleich zwischen PC und Handy die Verbindung in den Einstellungen einschalten.</small><small class="mono" style="color:var(--txt-3);word-break:break-all">${h(app)}</small></div></div></div>
        <div class="card"><div class="card-h"><h3>So läuft der Wareneingang</h3></div><div class="card-b"><div class="fld-steps" style="display:flex;flex-direction:column;gap:10px">${[['QR-Bogen drucken', 'ein Code je Bestellposition, mit der Bestellung erzeugt'], ['Handy scannt', 'Lager-App oder normale Kamera – der Code ist ein Link in diese App'], ['OK oder beschädigt', 'Lagerplatz wird vorgeschlagen; Schaden mit Foto meldet sich selbst beim Lieferanten'], ['Letzte Position', 'Auftrag wird montagebereit, Kunde erhält den Terminlink']].map((x, i) => `<div class="fld-step"><span class="n">${i + 1}</span><div><b>${x[0]}</b><small>${x[1]}</small></div></div>`).join('')}</div></div></div>
        <div class="card"><div class="card-h"><h3>Lagerplätze</h3></div><div class="card-b"><div class="dl"><dt>Regal A</dt><dd>Grossteile: Wannen, Duschwannen</dd><dt>Regal B</dt><dd>Keramik, Möbel, Spiegel, Radiatoren</dd><dt>Regal C</dt><dd>Kleinteile, Armaturen, Material</dd><dt>K-Fächer</dt><dd>Kommission je Auftrag (K-0142 …)</dd></div></div></div>
      </div></div></div>`;
};
Desk.titel.lager = 'Lager und QR-Codes';
Act.lagerk = {
  auf(el) { S.ui.lagerOffen = S.ui.lagerOffen === el.dataset.id ? null : el.dataset.id; Nav.zeichnen(); },
  qr(el) { const lp = Q.lagerposition(el.dataset.id); const a = Q.auftrag(lp.auftragId); UI.dialog({ titel: lp.name, unter: a.nr + ' · ' + lp.code, weite: 'slim', inhalt: `<div class="qr-big">${BWQR.svg(Mail.link('scan', lp.code), { size: 320, margin: 2 })}<small style="color:var(--txt-2);text-align:center">Mit dem Handy scannen: öffnet die Lager-App und bucht diese Position.</small></div>`, aktionen: [{ text: 'Schliessen', art: 'primary' }] }); }
};
