/* ==================================================================
   66 · Konsole: Termine und Montage, Showroom-Termine
   ================================================================== */
Desk.seiten.termine = () => {
  const heute = D.heute();
  const ts = DB.termine.filter(t => t.status !== 'abgesagt').map(t => ({ t, a: Q.auftrag(t.auftragId) })).filter(x => x.a).sort((x, y) => x.t.datum.localeCompare(y.t.datum));
  const kommend = ts.filter(x => x.t.datum >= heute && x.t.status !== 'erledigt'); const vergangen = ts.filter(x => x.t.datum < heute || x.t.status === 'erledigt');
  const bereit = DB.auftraege.filter(a => a.status === 'bereit');
  const zeile = x => { const p = Q.partner(x.t.partnerId); const k = Q.kunde(x.a.kundeId); const ob = Q.objekt(x.a.objektId); return `<tr class="click" data-act="nav.gehe" data-r="auftrag/${x.a.id}/termin"><td><b>${Fmt.wochentag(x.t.datum)} ${Fmt.datum(x.t.datum)}</b><br><small>${h(x.t.von)} – ${h(x.t.bis)} · ${x.t.dauerTage} ${x.t.dauerTage === 1 ? 'Tag' : 'Tage'}</small></td><td><b>${h(x.a.nr)}</b> · ${h(Dom.kundeName(k))}<br><small style="color:var(--txt-3)">${h(ob ? ob.strasse + ', ' + ob.ort : '')}</small></td><td>${h(p ? p.name : '–')}${x.t.monteur ? '<br><small>' + h(x.t.monteur) + '</small>' : ''}</td><td><span class="chip st dot st-${x.t.status}">${x.t.status === 'vorgeschlagen' ? 'Partner offen' : Dom.statusText(x.t.status)}</span></td><td><small>${x.t.quelle === 'kunde-online' ? 'online gewählt' : x.t.quelle === 'partner' ? 'Partner' : 'Telefon'}</small></td></tr>`; };
  return `<div class="pg">
    ${bereit.length ? `<div class="banner warn"><span class="ic">${ic('i-kalender')}</span><div><b>${bereit.length} ${bereit.length === 1 ? 'Auftrag wartet' : 'Aufträge warten'} auf den Kundentermin:</b> ${bereit.map(a => `<a href="#/auftrag/${a.id}/termin">${h(a.nr)} ${h(Dom.kundeName(Q.kunde(a.kundeId)))}</a>`).join(', ')}</div></div>` : ''}
    <div class="tbl-wrap"><div class="tbl-tools"><h3 style="font-size:14px;font-weight:700">Kommende Montagen</h3><div class="tb-sp"></div><span class="chip">${kommend.length}</span></div><div class="tbl-scroll"><table class="tbl"><thead><tr><th>Termin</th><th>Auftrag</th><th>Partnerbetrieb</th><th>Status</th><th>Quelle</th></tr></thead><tbody>${kommend.length ? kommend.map(zeile).join('') : '<tr><td colspan="5"><div class="empty"><b>Keine kommenden Montagen</b></div></td></tr>'}</tbody></table></div></div>
    <div class="tbl-wrap"><div class="tbl-tools"><h3 style="font-size:14px;font-weight:700">Erledigt</h3></div><div class="tbl-scroll"><table class="tbl"><thead><tr><th>Termin</th><th>Auftrag</th><th>Partnerbetrieb</th><th>Status</th><th>Quelle</th></tr></thead><tbody>${vergangen.map(zeile).join('') || '<tr><td colspan="5"><div class="empty"><b>Noch nichts</b></div></td></tr>'}</tbody></table></div></div>
  </div>`;
};
Desk.titel.termine = 'Termine und Montage';

Desk.seiten.showroom = () => {
  const heute = D.heute();
  const ts = DB.showroomTermine.filter(t => t.status !== 'abgesagt').sort((x, y) => (x.datum + x.von).localeCompare(y.datum + y.von));
  const kommend = ts.filter(t => t.datum >= heute); const vergangen = ts.filter(t => t.datum < heute);
  Desk.tools(`<button class="btn primary" data-act="showroom.neu">${ic('i-plus')} Termin erfassen</button>`);
  const zeile = t => { const p = Q.partner(t.partnerId); const k = Q.kunde(t.kundeId); return `<tr><td><b>${Fmt.wochentag(t.datum)} ${Fmt.datum(t.datum)}</b><br><small>${h(t.von)} – ${h(t.bis)}${t.hospitality ? ' · ☕ Kaffee und Gipfeli' : ''}</small></td><td><b>${h(t.kundeName || Dom.kundeName(k))}</b><br><small style="color:var(--txt-3)">${h(t.thema || 'Beratung')}</small></td><td>${p ? h(p.name) + '<br><small style="color:var(--txt-3)">' + (p.modell === 'plus' ? 'Partner Plus' : 'Partner Basis') + '</small>' : '<small>direkt</small>'}</td><td><small>${h((Q.benutzer(t.beraterId) || {}).name || '–')}</small></td><td><span class="chip st dot st-${t.status}">${Dom.statusText(t.status)}</span></td><td class="r"><div class="row" style="justify-content:flex-end;gap:4px">${t.status === 'angefragt' ? `<button class="btn sm primary" data-act="showroom.bestaetigen" data-id="${t.id}">Bestätigen</button>` : ''}${t.kundeId ? `<button class="btn sm" data-act="offerte.start" data-kunde="${h(t.kundeId)}">Offerte</button>` : `<button class="btn sm ghost" data-act="showroom.kunde" data-id="${t.id}">Kunde anlegen</button>`}<button class="btn sm ghost icon" data-act="showroom.absagen" data-id="${t.id}" title="Absagen">${ic('i-x')}</button></div></td></tr>`; };
  return `<div class="pg">
    <div class="banner"><span class="ic">${ic('i-showroom')}</span><div><b>Beratung 60 Minuten, Di–Sa.</b> Partnerbetriebe buchen über ihr Portal; Samstag-Vormittage mit Kaffee und Gipfeli sind Partner Plus vorbehalten. Der Kunde bleibt dem Partner zugeordnet – das steht später auf der Offerte.</div></div>
    <div class="tbl-wrap"><div class="tbl-tools"><h3 style="font-size:14px;font-weight:700">Kommende Termine</h3><div class="tb-sp"></div><span class="chip warn">${kommend.filter(t => t.status === 'angefragt').length} Anfragen</span></div><div class="tbl-scroll"><table class="tbl"><thead><tr><th>Termin</th><th>Kunde</th><th>Partner</th><th>Beratung</th><th>Status</th><th></th></tr></thead><tbody>${kommend.map(zeile).join('') || '<tr><td colspan="6"><div class="empty"><b>Keine Termine</b></div></td></tr>'}</tbody></table></div></div>
    ${vergangen.length ? `<div class="tbl-wrap"><div class="tbl-tools"><h3 style="font-size:14px;font-weight:700">Vergangen</h3></div><div class="tbl-scroll"><table class="tbl"><tbody>${vergangen.map(zeile).join('')}</tbody></table></div></div>` : ''}
  </div>`;
};
Desk.titel.showroom = 'Showroom-Termine';

Act.showroom = {
  async neu() { const w = await UI.formular('Showroom-Termin erfassen', [{ k: 'datum', label: 'Datum', typ: 'date', wert: D.plus(D.heute(), 1), pflicht: true }, { k: 'von', label: 'Von', typ: 'time', wert: '10:00', pflicht: true }, { k: 'kundeName', label: 'Kunde', pflicht: true }, { k: 'thema', label: 'Thema' }, { k: 'partnerId', label: 'Partnerbetrieb', typ: 'select', optionen: [{ v: '', t: 'direkt' }].concat(DB.partner.map(p => ({ v: p.id, t: p.name }))) }, { k: 'hospitality', label: 'Kaffee und Gipfeli', typ: 'schalter' }], 'Eintragen'); if (!w) return; Store.aendern('Showroom-Termin eingetragen', db => { const t = Dom.showroomTerminAnfragen(db, Object.assign(w, { status: 'bestaetigt', beraterId: S.benutzerId })); }); Nav.zeichnen(); },
  bestaetigen(el) { Store.aendern('Termin bestätigt', db => Dom.showroomTerminBestaetigen(db, db.showroomTermine.find(x => x.id === el.dataset.id))); Nav.zeichnen(); },
  absagen(el) { Store.aendern('Termin abgesagt', db => { const t = db.showroomTermine.find(x => x.id === el.dataset.id); t.status = 'abgesagt'; Store.log('showroom', 'Showroom-Termin ' + Fmt.datum(t.datum) + ' ' + t.von + ' abgesagt', null, '✖️'); }); Nav.zeichnen(); },
  async kunde(el) { const t = Q.showroomTermin(el.dataset.id); const teile = (t.kundeName || '').split(' '); const w = await UI.formular('Kunde anlegen', Kunden.FELDER({ anrede: '', vorname: teile.slice(0, -1).join(' '), name: teile.slice(-1)[0] || '', typ: 'privat' }), 'Anlegen'); if (!w) return; let id; Store.aendern('Kunde angelegt', db => { const k = Object.assign({ id: uid('k'), nr: Dom.nrNeu(db, 'kunde'), herkunft: t.partnerId ? 'partner' : 'showroom', partnerId: t.partnerId || null, erstellt: D.jetztIso() }, w); db.kunden.push(k); const ob = { id: uid('ob'), kundeId: k.id, bezeichnung: 'Bad', strasse: k.strasse, plz: k.plz, ort: k.ort, gebaeudetyp: 'efh', stockwerk: 0, lift: false, art: 'sanierung', baujahrVor1990: false, eigentum: 'eigentum', zugang: '', verwaltung: '' }; db.objekte.push(ob); k.objektId = ob.id; db.showroomTermine.find(x => x.id === t.id).kundeId = k.id; id = k.id; }); Nav.zeichnen(); }
};
