/* ==================================================================
   67 · Konsole: Partnerbetriebe
   Die zweite Kundengruppe: externe Sanitaerbetriebe, die Kunden
   bringen und montieren. Modell, Provisionen, Portal-Link.
   ================================================================== */
Desk.seiten.partner = () => {
  Desk.tools(`<button class="btn" data-act="partnerk.neu">${ic('i-plus')} Partner aufnehmen</button>`);
  const abo = sum(DB.partner.filter(p => p.modell === 'plus'), p => p.aboChf);
  return `<div class="pg">
    <div class="kpis"><div class="kpi"><span class="lbl">Partnerbetriebe</span><span class="val">${DB.partner.length}</span><span class="dt">${DB.partner.filter(p => p.modell === 'plus').length} Partner Plus</span></div><div class="kpi"><span class="lbl">Abo-Erlöse</span><span class="val">${Fmt.chf(abo)}</span><span class="dt">pro Monat, wiederkehrend</span></div><div class="kpi"><span class="lbl">Kunden über Partner</span><span class="val">${DB.kunden.filter(k => k.partnerId).length}</span><span class="dt">von ${DB.kunden.length}</span></div><div class="kpi"><span class="lbl">Montagen vermittelt</span><span class="val">${DB.auftraege.filter(a => a.partnerId && a.status !== 'storniert').length}</span></div></div>
    <div class="pgrid two">${DB.partner.map(p => { const auftr = DB.auftraege.filter(a => a.status !== 'storniert' && (a.partnerId === p.id || (Q.kunde(a.kundeId) || {}).partnerId === p.id)); const tipp = auftr.filter(a => (Q.kunde(a.kundeId) || {}).partnerId === p.id); const verm = auftr.filter(a => a.partnerId === p.id && a.montage.length); const termine = DB.termine.filter(t => t.partnerId === p.id && ['vorgeschlagen', 'bestaetigt'].includes(t.status)); return `<div class="card"><div class="card-h"><h3>${h(p.name)}</h3><span class="chip ${p.modell === 'plus' ? 'tint' : ''}">${p.modell === 'plus' ? 'Partner Plus · CHF ' + p.aboChf + '/Monat' : 'Partner Basis · gratis'}</span></div><div class="card-b stack">
      <div class="dl"><dt>Kontakt</dt><dd>${h(p.kontakt)} · ${h(p.telefon)} · ${h(p.email)}</dd><dt>Ort</dt><dd>${h(p.strasse)}, ${h(p.plz)} ${h(p.ort)}</dd><dt>Monteure</dt><dd>${h((p.monteure || []).join(', '))}</dd><dt>Seit</dt><dd>${Fmt.datum(p.seit)} · ${h(p.text || '')}</dd></div>
      <div class="kpis" style="grid-template-columns:repeat(4,1fr);gap:8px"><div class="kpi" style="padding:10px"><span class="lbl">Kunden gebracht</span><span class="val" style="font-size:20px">${tipp.length}</span></div><div class="kpi" style="padding:10px"><span class="lbl">Montagen</span><span class="val" style="font-size:20px">${verm.length}</span><span class="dt">${termine.length} offen</span></div><div class="kpi" style="padding:10px"><span class="lbl">Tippgeber an Partner</span><span class="val" style="font-size:20px">${Fmt.chfKurz(sum(tipp, a => a.total * p.provisionTipp / 100))}</span><span class="dt">${p.provisionTipp} % Material</span></div><div class="kpi" style="padding:10px"><span class="lbl">Vermittlung an uns</span><span class="val" style="font-size:20px">${p.modell === 'plus' ? '–' : Fmt.chfKurz(sum(verm, a => sum(a.montage, m => m.vk) * p.provisionVermittlung / 100))}</span><span class="dt">${p.modell === 'plus' ? 'im Abo' : p.provisionVermittlung + ' % Montage'}</span></div></div>
      <div class="row wrap" style="gap:8px"><a class="btn primary" href="${h(Mail.link('p', p.token))}" target="_blank" rel="noopener">${ic('i-link')} Partnerportal öffnen</a><button class="btn" data-act="partnerk.modell" data-id="${p.id}">${p.modell === 'plus' ? 'Auf Basis setzen' : 'Auf Plus setzen'}</button><button class="btn ghost" data-act="partnerk.bearbeiten" data-id="${p.id}">${ic('i-stift')} Bearbeiten</button></div></div></div>`; }).join('')}</div>
    <div class="card"><div class="card-h"><h3>Das Partnermodell</h3><span class="chip">transparent, ohne Preisabsprachen</span></div><div class="card-b"><div class="tbl-scroll"><table class="tbl"><thead><tr><th></th><th>Partner Basis</th><th>Partner Plus</th></tr></thead><tbody>${[['Preis', 'gratis', 'CHF 149 pro Monat'], ['Showroom-Slots', 'Standard (Di–Fr, Sa-Nachmittag)', 'Prime-Slots: Samstag-Vormittag mit Kaffee und Gipfeli, Di/Do-Abend'], ['Vermittlungsprovision an den Showroom', '6 % auf vermittelte Montagen', 'keine'], ['Montageaufträge aus dem Showroom', 'nach Verfügbarkeit', 'Vorrang'], ['Co-Branding auf der Offerte', '–', 'ja'], ['Tippgeberprovision an den Partner', '5 % auf Materialumsatz gebrachter Kunden', '5 % auf Materialumsatz gebrachter Kunden'], ['Lieferstatus der eigenen Kunden im Portal', 'ja', 'ja']].map(r => `<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div></div></div>
  </div>`;
};
Desk.titel.partner = 'Partnerbetriebe';
Act.partnerk = {
  modell(el) { Store.aendern('Partnermodell geändert', db => { const p = db.partner.find(x => x.id === el.dataset.id); if (p.modell === 'plus') { p.modell = 'basis'; p.aboChf = 0; p.provisionVermittlung = 6; } else { p.modell = 'plus'; p.aboChf = 149; p.provisionVermittlung = 0; } Store.log('partner', p.name + ' ist jetzt ' + (p.modell === 'plus' ? 'Partner Plus' : 'Partner Basis'), null, '🤝'); }); Nav.zeichnen(); },
  async bearbeiten(el) { const p = Q.partner(el.dataset.id); const w = await UI.formular(p.name, [{ k: 'name', label: 'Firma', wert: p.name, pflicht: true }, { k: 'kontakt', label: 'Kontakt', wert: p.kontakt }, { k: 'email', label: 'E-Mail', wert: p.email }, { k: 'telefon', label: 'Telefon', wert: p.telefon }, { k: 'strasse', label: 'Strasse', wert: p.strasse }, { k: 'plz', label: 'PLZ', wert: p.plz }, { k: 'ort', label: 'Ort', wert: p.ort }, { k: 'monteure', label: 'Monteure (mit Komma)', wert: (p.monteure || []).join(', '), breit: true }, { k: 'provisionTipp', label: 'Tippgeber %', typ: 'number', wert: p.provisionTipp }, { k: 'provisionVermittlung', label: 'Vermittlung %', typ: 'number', wert: p.provisionVermittlung }]); if (!w) return; Store.aendern('Partner gespeichert', db => { const x = db.partner.find(y => y.id === p.id); Object.assign(x, w); x.monteure = String(w.monteure || '').split(',').map(s => s.trim()).filter(Boolean); }); Nav.zeichnen(); },
  async neu() { const w = await UI.formular('Partner aufnehmen', [{ k: 'name', label: 'Firma', pflicht: true }, { k: 'kontakt', label: 'Kontakt' }, { k: 'email', label: 'E-Mail' }, { k: 'telefon', label: 'Telefon' }, { k: 'ort', label: 'Ort' }, { k: 'modell', label: 'Modell', typ: 'select', optionen: [{ v: 'basis', t: 'Partner Basis (gratis, 6 % Vermittlung)' }, { v: 'plus', t: 'Partner Plus (CHF 149/Monat)' }] }], 'Aufnehmen'); if (!w) return; Store.aendern('Partner aufgenommen', db => { db.partner.push({ id: uid('P'), name: w.name, kontakt: w.kontakt, email: w.email, telefon: w.telefon, strasse: '', plz: '', ort: w.ort, modell: w.modell, aboChf: w.modell === 'plus' ? 149 : 0, provisionVermittlung: w.modell === 'plus' ? 0 : 6, provisionTipp: 5, token: token(), monteure: [w.kontakt].filter(Boolean), slots: { tage: [1, 2, 3, 4, 5], vormittag: '07:30', nachmittag: '13:00' }, belegt: [], aktiv: true, seit: D.heute(), text: '' }); }); Nav.zeichnen(); }
};
